language: go

install:
  - go get -t -v ./...
  - go get -v golang.org/x/lint/golint

matrix:
  include:
    - name: "go1.12.x"
      go: 1.12.x
      script: make test
    - name: "go1.12.x race"
      go: 1.12.x
      script: make testrace
    - name: "go1.12.x windows"
      go: 1.12.x
      # NB: "env: GOOS=windows" does not have the desired effect.
      script: GOOS=windows go build -v ./...
    - name: "go1.12.x freebsd"
      go: 1.12.x
      # NB: "env: GOOS=freebsd" does not have the desired effect.
      script: GOOS=freebsd go build -v ./...
    - name: "go1.13.x"
      go: 1.13.x
      script: make test
    - name: "go1.13.x race"
      go: 1.13.x
      script: make testrace

notifications:
  email:
    recipients:
      - peter@cockroachlabs.com
    on_success: never
    on_failure: always
