name: Test
on:
  pull_request:
  push:
    branches: [master]
jobs:
  test:
    name: go${{ matrix.go }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: [1.12, 1.13]
        os: [ubuntu-latest, macOS-latest, windows-latest]

        # Only test go1.13 on linux.
        exclude:
        - go: 1.13
          os: macOS-latest
        - go: 1.13
          os: windows-latest

    steps:
    - name: Set up go${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get -x -v golang.org/x/lint/golint

    - name: Test
      run: |
        export PATH=$(go env GOPATH)/bin:${PATH}
        go test ./...

    # Only run race tests on Linux
    - name: Testrace
      run: |
        export PATH=$(go env GOPATH)/bin:${PATH}
        go test -race ./...
      if: matrix.os == 'ubuntu-latest'

    # Verify that go generate can compile the necessary binaries. We
    # only need to do this on one job.
    - name: Generate
      run: go generate ./...
      if: matrix.go == '1.13' && matrix.os == 'ubuntu-latest'

    # Verify that we can build with GOOS=freebsd. We only need to do
    # this on one job.
    - name: Build (freebsd)
      run: GOOS=freebsd go build ./...
      if: matrix.go == '1.13' && matrix.os == 'ubuntu-latest'
